In [1]:
# 배열 만들기
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
import numpy as np

np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
print(np.array([3,1.4,2,3,4.5]))

# 넘파이의 array는 단일 데이터 타입
# 정수, 실수 >> 실수 변경됨

[3.  1.4 2.  3.  4.5]


In [5]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [11]:
print(np.array([1,2,3,4]))
print()
print(np.array([1,2,3,4],dtype=float))

print()
arr = np.array([1,2,3,4],dtype=float)
print(arr)
print(arr.dtype)
# astype() :  데이터 타입 변경
print(arr.astype(int))

[1 2 3 4]

[1. 2. 3. 4.]

[1. 2. 3. 4.]
float64
[1 2 3 4]


In [16]:
# 다양한 배열 만들기
print(np.zeros(10, dtype=int))
print()

print(np.ones((3, 5), dtype=float))
print()

print(np.arange(0, 20, 2))
print()

print(np.linspace(0, 1, 5))

[0 0 0 0 0 0 0 0 0 0]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[ 0  2  4  6  8 10 12 14 16 18]

[0.   0.25 0.5  0.75 1.  ]


In [17]:
# 난수로 채워진 배열 만들기
print(np.random.random((2, 2)))
print()

print(np.random.normal(0, 1, (2, 2)))
print()

print(np.random.randint(0, 10, (2, 2)))

[[0.39834315 0.89479676]
 [0.43770215 0.98578184]]

[[ 0.59076673  2.52333395]
 [ 0.0999416  -0.24452999]]

[[7 4]
 [0 9]]


In [19]:
# 배열의 기초
x2 = np.random.randint(10, size=(3, 4))

print(x2.ndim)
print()

print(x2.shape)
print()

print(x2.size)
print()

print(x2.dtype)
print()

2

(3, 4)

12

int32



In [25]:
# indexing
x = np.arange(7)

print(x[3])
print()

# print(x[7])
# print()
# index 7 is out of bounds for axis 0 with size 7

x[0] = 10
print(x)

3

[10  1  2  3  4  5  6]


In [41]:
# slicing
x = np.arange(7)

print(x[1:4])
print()

print(x[1:])
print()

print(x[:4])
print()

print(x[::2])
print()
print(x[::-1]) # 역순 출력 (***)

[1 2 3]

[1 2 3 4 5 6]

[0 1 2 3]

[0 2 4 6]

[6 5 4 3 2 1 0]


In [28]:
# reshape (****)
x = np.arange(8)
print(x.shape)

x2 = x.reshape((2, 4))
x2.shape

(8,)


(2, 4)

In [29]:
# concatenate
x = np.array([0, 1, 2])
y = np.array([3, 4, 5])
np.concatenate([x, y])

array([0, 1, 2, 3, 4, 5])

In [34]:
print(np.arange(4).reshape(2,2))
matrix = np.arange(4).reshape(2, 2)
np.concatenate([matrix, matrix], axis=0)

[[0 1]
 [2 3]]


array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [35]:
matrix = np.arange(4).reshape(2, 2)
print(matrix)
np.concatenate([matrix, matrix], axis=1)

[[0 1]
 [2 3]]


array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [38]:
# split
matrix = np.arange(16).reshape(4, 4)
print(matrix)
print()

upper, lower = np.split(matrix, [3], axis=0)
print(upper)
print()
print(lower)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]]


In [39]:
matrix = np.arange(16).reshape(4, 4)
print(matrix)
print()

left, right = np.split(matrix, [3], axis=1)
print(left)
print()
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]

[[ 3]
 [ 7]
 [11]
 [15]]


In [42]:
# array의 모든 원소에 5를 더해서 만드는 함수
def add_five_to_array(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = values[i] +5
        
    return output

values = np.random.randint(1,10,size=5)
add_five_to_array(values)

array([12.,  8.,  9.,  6.,  9.])

In [43]:
# 만약 array가 너무 크다면?
big_array = np.random.randint(1, 100, size=10000000)
add_five_to_array(big_array)
big_array + 5

array([73, 27, 45, ..., 88, 94, 31])

In [44]:
x = np.arange(4)

print(x + 5)

print(x - 5)

print(x * 5)

print(x / 5)


[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]
[0.  0.2 0.4 0.6]


In [47]:
x1 = np.arange(4).reshape((2, 2))
x2 = np.random.randint(10, size=(2, 2))

print(x1 + x2)
print(x1- x2)

[[9 6]
 [9 9]]
[[-9 -4]
 [-5 -3]]


In [48]:
# 집계함수
x = np.arange(8).reshape((2, 4))
print(np.sum(x))

print(np.min(x))

print(np.max(x))

print(np.mean(x))

28
0
7
3.5


In [49]:
x = np.arange(8).reshape((2, 4))
print(np.sum(x, axis=0))
# array([ 4, 6, 8, 10])
print(np.sum(x, axis=1))

[ 4  6  8 10]
[ 6 22]


In [50]:
# 마스킹 연산
x = np.arange(5)

print(x < 3)

print(x > 5)

print(x[x < 3])

[ True  True  True False False]
[False False False False False]
[0 1 2]
